In [1]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split

In [2]:
df = pd.read_csv('datasets/mushrooms.csv')
df.head(20)

type cap_shape cap_surface cap_color bruises odor gill_attachment  \
0     p         x           s         n       t    p               f   
1     e         x           s         y       t    a               f   
2     e         b           s         w       t    l               f   
3     p         x           y         w       t    p               f   
4     e         x           s         g       f    n               f   
5     e         x           y         y       t    a               f   
6     e         b           s         w       t    a               f   
7     e         b           y         w       t    l               f   
8     p         x           y         w       t    p               f   
9     e         b           s         y       t    a               f   
10    e         x           y         y       t    l               f   
11    e         x           y         y       t    a               f   
12    e         b           s         y       t    a               f   
13    p         x           y         w       t    p               f   
14    e         x           f         n       f    n               f   
15    e         s           f         g       f    n               f   
16    e         f           f         w       f    n               f   
17    p         x           s         n       t    p               f   
18    p         x           y         w       t    p               f   
19    p         x           s         n       t    p               f   

   gill_spacing gill_size gill_color  ... stalk_surface_below_ring  \
0             c         n          k  ...                        s   
1             c         b          k  ...                        s   
2             c         b          n  ...                        s   
3             c         n          n  ...                        s   
4             w         b          k  ...                        s   
5             c         b          n  ...                        s   
6             c         b          g  ...                        s   
7             c         b          n  ...                        s   
8             c         n          p  ...                        s   
9             c         b          g  ...                        s   
10            c         b          g  ...                        s   
11            c         b          n  ...                        s   
12            c         b          w  ...                        s   
13            c         n          k  ...                        s   
14            w         b          n  ...                        f   
15            c         n          k  ...                        s   
16            w         b          k  ...                        s   
17            c         n          n  ...                        s   
18            c         n          n  ...                        s   
19            c         n          k  ...                        s   

   stalk_color_above_ring stalk_color_below_ring veil_type veil_color  \
0                       w                      w         p          w   
1                       w                      w         p          w   
2                       w                      w         p          w   
3                       w                      w         p          w   
4                       w                      w         p          w   
5                       w                      w         p          w   
6                       w                      w         p          w   
7                       w                      w         p          w   
8                       w                      w         p          w   
9                       w                      w         p          w   
10                      w                      w         p          w   
11                      w                      w         p          w   
12                      w                      w         p          w 

In [3]:
print(df.shape)

(8124, 23)


## Convert alphabets to numbers
the data is in alphebeticla e.g o represents orange, b represents blue
we will now map each rows letters with a number

In [3]:
le = LabelEncoder()
#applies tranformation on each method
ds = df.apply(le.fit_transform)


In [17]:
(ds.head(50))

type  cap_shape  cap_surface  cap_color  bruises  odor  gill_attachment  \
0      1          5            2          4        1     6                1   
1      0          5            2          9        1     0                1   
2      0          0            2          8        1     3                1   
3      1          5            3          8        1     6                1   
4      0          5            2          3        0     5                1   
5      0          5            3          9        1     0                1   
6      0          0            2          8        1     0                1   
7      0          0            3          8        1     3                1   
8      1          5            3          8        1     6                1   
9      0          0            2          9        1     0                1   
10     0          5            3          9        1     3                1   
11     0          5            3          9        1     0                1   
12     0          0            2          9        1     0                1   
13     1          5            3          8        1     6                1   
14     0          5            0          4        0     5                1   
15     0          4            0          3        0     5                1   
16     0          2            0          8        0     5                1   
17     1          5            2          4        1     6                1   
18     1          5            3          8        1     6                1   
19     1          5            2          4        1     6                1   
20     0          0            2          9        1     0                1   
21     1          5            3          4        1     6                1   
22     0          0            3          9        1     3                1   
23     0          0            3          8        1     0                1   
24     0          0            2          8        1     3                1   
25     1          2            2          8        1     6                1   
26     0          5            3          9        1     0                1   
27     0          5            3          8        1     3                1   
28     0          2            0          4        0     5                1   
29     0          5            2          9        1     0                1   
30     0          0            2          9        1     3                1   
31     1          5            3          8        1     6                1   
32     0          5            3          9        1     3                1   
33     0          5            3          4        1     3                1   
34     0          0            3          9        1     3                1   
35     0          5            0          9        1     3                1   
36     0          4            0          3        0     5                1   
37     1          5            3          4        1     6                1   
38     0          5            0          9        1     0                1   
39     0          0            2          9        1     3                1   
40     0          0            3          9        1     0                1   
41     0          5            3          9        1     3                1   
42     0          5            0          4        0     5                1   
43     1          5            3          8        1     6                1   
44     0          5            2          9        1     0                1   
45     0          5            3          8        1     0                1   
46     0          5            3          9        1     3                1   
47     0          5            2          8        1     3                1   
48     0          5            3          9        1     3                1   
49     0          2            3          9        1  

In [4]:
data = ds.values
print(data.shape)
print(type(data))
print(data[:5,:])


(8124, 23)
<class 'numpy.ndarray'>
[[1 5 2 4 1 6 1 0 1 4 0 3 2 2 7 7 0 2 1 4 2 3 5]
 [0 5 2 9 1 0 1 0 0 4 0 2 2 2 7 7 0 2 1 4 3 2 1]
 [0 0 2 8 1 3 1 0 0 5 0 2 2 2 7 7 0 2 1 4 3 2 3]
 [1 5 3 8 1 6 1 0 1 5 0 3 2 2 7 7 0 2 1 4 2 3 5]
 [0 5 2 3 0 5 1 1 0 4 1 3 2 2 7 7 0 2 1 0 3 0 1]]


In [5]:
data_x = data[:,1:]
data_y = data[:,0]

In [6]:
x_train, x_test, y_train, y_test = train_test_split(data_x,data_y, test_size = 0.2)

In [15]:
print(x_train.shape, y_train.shape)
print(x_test.shape, y_test.shape)

(6499, 22) (6499,)
(1625, 22) (1625,)


In [16]:
np.unique(y_train)

array([0, 1])

# Classifier

In [7]:
def prior_prob( y_train, label):
    total_examples = y_train.shape[0]
    class_examples = np.sum(y_train==label)
    
    return (class_examples/float(total_examples))

In [8]:
y = np.array([0,5,5,1,1,1,1,0,0,0])
prior_prob(y,5)

0.2

In [9]:
def cond_prob(x_train, y_train, feature_col, feature_val, label):
    x_filtered = x_train[y_train==label]
    numerator = np.sum(x_filtered[:,feature_col] == feature_val)
    denominator = np.sum(y_train==label)
    
    return numerator/float(denominator)

In [10]:
def predict(x_train, y_train, xtest):
    classes = np.unique(y_train)
    n_features = x_train.shape[1]
    post_probs = []
    
    for label in classes:
        likelihood = 1.0
        prior = prior_prob(y_train, label)
        for f in range(n_features):
            cond = cond_prob(x_train, y_train, f, xtest[f], label)
            likelihood *= cond
        
        post = likelihood*prior
        post_probs.append(post)
    pred = np.argmax(post_probs)
    return pred

In [35]:
output = predict(x_train, y_train, x_test[1])

In [37]:
print(output,y_test[1])

1 1


In [11]:
def score(x_train, y_train, x_test, y_test):
    pred = []
    for i in range(x_test.shape[0]):
        pred_label = predict(x_train, y_train, x_test[i])
        pred.append(pred_label)
    pred = np.array(pred)
    accuracy = np.sum(pred==y_test)/y_test.shape[0]
    return accuracy

In [12]:
print(score(x_train, y_train, x_test, y_test))

0.9950769230769231
